# Generated by Django 4.2.30 on 2026-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcement_institution_visualidentity_pushdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
