# Generated by Django 4.2.30 on 2026-05-27 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pushdevice_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pinned', '-published_at', '-created_at'], 'verbose_name': 'Comunicado', 'verbose_name_plural': 'Comunicados'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AlterModelOptions(
            name='deliverylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de entrega', 'verbose_name_plural': 'Logs de entrega'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instituicao', 'verbose_name_plural': 'Instituicoes'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='pushdevice',
            options={'verbose_name': 'Dispositivo push', 'verbose_name_plural': 'Dispositivos push'},
        ),
        migrations.AlterModelOptions(
            name='visualidentity',
            options={'verbose_name': 'Identidade visual', 'verbose_name_plural': 'Identidades visuais'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('video', 'Video'), ('other', 'Outro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='channel',
            field=models.CharField(choices=[('push', 'Notificacao push')], default='push', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('viewed', 'Visualizado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='kind',
            field=models.CharField(choices=[('city_hall', 'Prefeitura'), ('council', 'Camara')], default='city_hall', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Cidadao'), ('manager', 'Gestor')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualidentity',
            name='primary_color',
            field=models.CharField(default='#0057A8', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor hexadecimal como #123ABC.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='visualidentity',
            name='secondary_color',
            field=models.CharField(default='#00A676', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor hexadecimal como #123ABC.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
