# Generated by Django 4.2.30 on 2026-06-06 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_unique_delivery_log_per_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(blank=True, max_length=180)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('request_type', models.CharField(choices=[('erasure', 'Exclusao de dados'), ('export', 'Exportacao de dados'), ('deactivation', 'Desativacao de conta')], default='erasure', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluida'), ('rejected', 'Rejeitada')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitacao LGPD',
                'verbose_name_plural': 'Solicitacoes LGPD',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_privacy_user_id_774cb5_idx'), models.Index(fields=['status', 'created_at'], name='api_privacy_status_b8aad2_idx'), models.Index(fields=['request_type', 'created_at'], name='api_privacy_request_d26edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='api_auditlo_actor_i_f8e456_idx'), models.Index(fields=['action', 'created_at'], name='api_auditlo_action_e69819_idx'), models.Index(fields=['target_type', 'target_id'], name='api_auditlo_target__da2d13_idx')],
            },
        ),
    ]
