# Generated by Django 4.2.30 on 2026-06-06 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_privacyrequest_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_devices', models.ManyToManyField(blank=True, related_name='segments', to='api.pushdevice')),
                ('users', models.ManyToManyField(blank=True, related_name='segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='api.segment'),
        ),
    ]
