# Generated by Django 4.2.30 on 2026-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_segment_announcement_segments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='privacyrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação LGPD', 'verbose_name_plural': 'Solicitações LGPD'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('video', 'Vídeo'), ('other', 'Outro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='channel',
            field=models.CharField(choices=[('push', 'Notificação push')], default='push', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='kind',
            field=models.CharField(choices=[('city_hall', 'Prefeitura'), ('council', 'Câmara')], default='city_hall', max_length=30),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='request_type',
            field=models.CharField(choices=[('erasure', 'Exclusão de dados'), ('export', 'Exportação de dados'), ('deactivation', 'Desativação de conta')], default='erasure', max_length=30),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('rejected', 'Rejeitada')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Cidadão'), ('manager', 'Gestor')], default='citizen', max_length=20),
        ),
    ]
