# Generated by Django 4.2 on 2026-06-23

from django.db import migrations, models


def grant_existing_managers_app_permissions(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.filter(user__is_staff=True).update(
        role='manager',
        can_control_access=True,
        can_manage_announcements=True,
        can_manage_visual_identity=True,
        can_view_manager_dashboard=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_control_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_announcements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_visual_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_manager_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_access_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            grant_existing_managers_app_permissions,
            migrations.RunPython.noop,
        ),
    ]
